# Generated by Django 3.1.7 on 2021-04-01 17:36

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_contact', phone_field.models.PhoneField(blank=True, help_text='Customer phone number', max_length=31)),
                ('room_category', models.CharField(choices=[('deluxe room', 'deluxe room'), ('super deluxe room', 'super deluxe room'), ('suite room', 'suite room')], default='deluxe room', max_length=50)),
                ('room_no', models.CharField(max_length=10)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('days', models.IntegerField(default=0)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
