# Generated by Django 3.1.7 on 2021-04-02 07:40

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='category',
            field=models.CharField(choices=[('deluxe room', 'deluxe room'), ('super deluxe room', 'super deluxe room'), ('suite room', 'suite room')], default='deluxe room', max_length=50),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='room_contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='state',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Booked', 'Booked'), ('Available', 'Available')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='customer_contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
