# Generated by Django 3.1.7 on 2021-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210402_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='checkin_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
    ]
