# Generated by Django 3.1.7 on 2021-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_bookroom_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
