# Generated by Django 3.1.7 on 2021-04-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20210409_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookroom',
            name='number_of_rooms',
        ),
    ]
